export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_WISHLIST_FAILED = 'ADD_TO_CART_FAILED';

export const FETCH_WISHLIST_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_WISHLIST_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_WISHLIST_FAILED = 'FETCH_CART_FAILED';

export const DELETE_WISHLIST_ITEM_REQUEST = 'DELETE_CART_ITEM_REQUEST';
export const DELETE_WISHLIST_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_WISHLIST_ITEM_FAILED = 'DELETE_CART_ITEM_FAILED';
